### ISSUE TITLE
blank page when non-english utf-8 character present in https://manager.ens.domains/name/example.eth/subdomains

### ISSUE THREAD

**Issue by afool41** [ensdomains/ui#11]
Page is blank when there is a non-english utf8 chinese character present in the subdomain page . 
Example URL :  https://manager.ens.domains/name/example.eth/subdomains  

However, I can still successfully set resolver in URL like https://manager.ens.domains/name/中文.example.eth .. So it's only a UI problem..

**Comment by jefflau** [comment]
Hi @afool41 - is this to do with this library or specific to the manager?

**Comment by afool41** [comment]
> Hi @afool41 - is this to do with this library or specific to the manager?

I am not sure which library you are refering to.. 
I think the problem is about the webpage itself..  
The webpage at manager.ens.domains/name/foo.eth/subdomains turns blank when you use a utf8 chinese character as a subdomain name.

**Comment by Arachnid** [comment]
@afool41 Can you provide an example? The one you linked to doesn't seem to have any subdomains.

**Comment by Arachnid** [comment]
Correction - I'm seeing the bug now. @jefflau try loading the /subdomains page in the issue description to see the bug in action.

**Comment by afool41** [comment]
> Correction - I'm seeing the bug now. @jefflau try loading the /subdomains page in the issue description to see the bug in action.

I don't know if example.eth has a utf8 chinese character subdomain, I was referring to example.eth as an example only..
The specific domain I know has utf8-chinese subdomains is cryptogr.eth -  https://manager.ens.domains/name/cryptogr.eth/subdomains  

Thanks for your help..

**Comment by jefflau** [comment]
Thanks. I'll close this issue for now and add it to the app repo
