### ISSUE TITLE
Can't pass ethers provider as a customProvider

### ISSUE THREAD

**Issue by perich** [ensdomains/ui#21]
When invoking `setupENS()` I'd like to pass an ethers provider. At AirSwap we've completely migrated away from Web3 and our apps are built exclusively on [Ethers](https://github.com/ethers-io/ethers.js/) now. However, it looks like the `customProvider` in the optional config only works with a Web3 provider.

Attempting to pass an Ethers provider will fail like in the error below:
<img width="597" alt="Screen Shot 2019-08-12 at 3 47 37 PM" src="https://user-images.githubusercontent.com/13304874/62893400-89300080-bd18-11e9-8723-2eea646588ad.png">

I notice that you also use Ethers in your `package.json`. Would you consider adding support for this? Or do you think your repo is too committed to Web3 at this point? 

I'm debating whether I should try to make this work myself or just completely stop using this library and try rolling my own ENS integration instead. Appreciate any input you have. Thanks!

**Comment by Arachnid** [comment]
Ethers somewhat overloads terminology here. An ethers "provider" is equivalent to a web3 instance in functionality. Where 'provider' is referred to outside Ethers, though, it's a bare RPC interface. This isn't web3-specific - providers are injected by Metmask and other integrations, and consumed by both ethers and web3. You should be able to pass in the same provider instance you're passing in to Ethers, to the ens integration.

**Comment by perich** [comment]
I see! Thanks for the insight. In my case, I create an ethers "provider" like so:

`const ethers = require('ethers')`
`const httpProvider = new ethers.providers.JsonRpcProvider(AIRSWAP_GETH_NODE_ADDRESS)`

and then I can use it with Ethers like this:

```
const myContract = new ethers.Contract(
    CONTRACT_ADDRESS,
    CONTRACT_ABI,
    httpProvider,
  )
```

However if I try to call `setupENS()` with the same provider..

`setupENS({ customProvider: httpProvider })`

..then I will experience the error found in the image above. So I'm not able to pass in the same provider instance unfortunately. Maybe I'm missing something?

**Comment by perich** [comment]
I think the problem is with this line here, where it assumes `customProvider` is a Web3Provider https://github.com/ensdomains/ui/blob/master/src/web3.js#L19

I think a possible fix is to detect if the `customProvider` is already an instantiated ethers provider, and then just set `provider = customProvider` in that case. I'll try it out.

**Comment by perich** [comment]
Ok, I made this fix locally and it resolved the issue. Everything is working well now :) 

Here is a PR: https://github.com/ensdomains/ui/pull/22

**Comment by Arachnid** [comment]
What Ethers calls a 'web3 provider' is a wrapper for the generic JSON-RPC provider interface defined in EIP 1193 and exported by Metamask and others. It's not specific to web3.

We're trying to avoid accepting input parameters from specific libraries, because when we originally did this we immediately ran into issues with APIs changing across versions, and because it makes assumptions about the library our users use. It's much cleaner to to accept something with a well documented API.

To solve your immediate issue, perhaps we could instead add an overload that takes an RPC endpoint URL instead of a provider?

**Comment by perich** [comment]
I see. That definitely makes sense to me. Is this more along the lines of what you are thinking?

https://github.com/ensdomains/ui/pull/22/files

If you would prefer to implement it yourselves, I can close the PR. Just let me know. Thanks!

**Comment by jefflau** [comment]
Sorry for the delayed response @perich. I think this looks good and we will implement this

**Comment by perich** [comment]
Hi @jefflau I see you've opened a branch to resolve this here: https://github.com/ensdomains/ui/commit/784f3d637e99f39fc7445f03f40c5a7a929d5579

as such I will close my identical PR: https://github.com/ensdomains/ui/pull/22

Thanks!
