### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by cgewecke** [ensdomains/ui#62]
Hi, thanks for writing this great lib.

Web3.js is extending its ENS wrapper to support `contentHash` (for [Web3 3392][1]) and would like to copy/adapt the encoding logic in [src/utils/contents][2] for that purpose.  

Was hoping to paste relevant license and authorship info but can't find the licensing here...

Could you provide any guidance about this? 

[1]: https://github.com/ethereum/web3.js/issues/3392
[2]: https://github.com/ensdomains/ui/blob/3e62e440b53466eeec9dd1c63d73924eefbd88c1/src/utils/contents.js#L1-L85

**Comment by jefflau** [comment]
Just pushed up our license to the repo

**Comment by cgewecke** [comment]
Sweet, thanks @jefflau.
